// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProdMon.Infrastructure.Data;

#nullable disable

namespace ProdMon.Infrastructure.Migrations
{
    [DbContext(typeof(ProdMonDbContext))]
    partial class ProdMonDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProdMon.Domain.Models.ArticleCode", b =>
                {
                    b.Property<string>("ArticleNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArticleDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArticleNumber");

                    b.ToTable("ArticleCodes");

                    b.HasData(
                        new
                        {
                            ArticleNumber = "55322234",
                            ArticleDescription = "Querlenker"
                        },
                        new
                        {
                            ArticleNumber = "123455",
                            ArticleDescription = "Test"
                        },
                        new
                        {
                            ArticleNumber = "05010292",
                            ArticleDescription = "Bremsscheibe"
                        });
                });

            modelBuilder.Entity("ProdMon.Domain.Models.MonitorEntry", b =>
                {
                    b.Property<string>("Dmc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CheckPointId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Dmc");

                    b.ToTable("MonitorEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
